language: java
sudo: required
jdk:
  - openjdk8
services:
  - mongodb
dist: trusty
before_install:
  - mongo --eval "db.createUser( { user: 'tokenuser', 'pwd': 'tokenpwd', roles: [ { role: 'read', db: 'tokendispenser' } ] } )"
