language: java
sudo: required
jdk:
  - openjdk8
dist: trusty
before_install:
  - sudo apt-key adv --keyserver "hkp://keyserver.ubuntu.com:80" --recv 0C49F3730359A14518585931BC711F9BA15703C6
  - echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
  - sudo apt update -qq
  - sudo apt install -qq mongodb-org
  - sudo service mongod start
  - "sudo mongo --eval \"db.createUser( { user: 'tokenuser', 'pwd': 'tokenpwd', roles: [ { role: 'read', db: 'tokendispenser' } ] } )\""
