language: java
sudo: required
jdk:
  - openjdk8
dist: trusty
before_install:
  - echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
  - sudo apt update -qq
  - sudo apt install -qq mongodb-org
  - "sudo mongo --eval 'db.createUser( { user: \"tokenuser\", \"pwd\": \"tokenpwd\", roles: [ { role: \"read\", db: \"tokendispenser\" } ] } )'"
